language: node_js
node_js:
  - "7"
cache:
  directories:
    - "node_modules"
before_install:
  - echo "this is a travis before_install test"
before_script:
  - echo "this is a travis before_script test"
after_success:
  - echo "this is a travis after_success test"
  - echo $TRAVIS_TEST_RESULT
after_failure:
  - echo "this is a travis after_failure test"
  - echo $TRAVIS_TEST_RESULT
